name: Build QA - Verify make targets prefix



on:
  workflow_dispatch:

  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'ChangeLog'
      - 'COPYING'
      - 'configure.scan'
      - 'packaging/**'
      - 'dev-tools/**'
      - '!dev-tools/libexec/get-release-*.sh'
      - 'doc/**'
      - 'etc/**'
      - 'install/**'
      - 'lib/*/IMPORT.defs'
      - 'lib/*/LICENSE'
      - 'README.md'

  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'ChangeLog'
      - 'COPYING'
      - 'configure.scan'
      - 'packaging/**'
      - 'dev-tools/**'
      - '!dev-tools/libexec/get-release-*.sh'
      - 'doc/**'
      - 'etc/**'
      - 'install/**'
      - 'lib/*/IMPORT.defs'
      - 'lib/*/LICENSE'
      - 'README.md'



jobs:
  build-qa-verify-make-targets-prefix:

    name: Verify make targets prefix
    runs-on: ubuntu-20.04
    container: ciready/ubuntu:20.04-ci-c



    ###
    ### Steps to run
    ###
    steps:



      ### Fetch the code
      #
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      # Work around the fix for CVE-2022-24765
      - run: git config --global --add safe.directory $GITHUB_WORKSPACE || true



      ### Build
      #
      - run: ./dev-tools/install-dev-software.sh
      - run: ./bootstrap.sh
      - run: ./configure --enable-option-checking=fatal --enable-everything
      - run: make -j4



      ### Verify
      #
      - run: ./dev-tools/libexec/verify-make-targets-prefix.sh
