name: Build QA - Valgrind



on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/*.md'
      - '.github/workflows/**'
      - '.gitignore'
      - 'ChangeLog'
      - 'COPYING'
      - 'configure.scan'
      - 'contrib/**'
      - 'dev-tools/**'
      - '!dev-tools/libexec/get-release-*.sh'
      - 'doc/**'
      - 'etc/**'
      - 'install/**'
      - 'lib/*/IMPORT.defs'
      - 'lib/*/LICENSE'
      - 'README.md'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/*.md'
      - '.github/workflows/**'
      - '.gitignore'
      - 'ChangeLog'
      - 'COPYING'
      - 'configure.scan'
      - 'contrib/**'
      - 'dev-tools/**'
      - '!dev-tools/libexec/get-release-*.sh'
      - 'doc/**'
      - 'etc/**'
      - 'install/**'
      - 'lib/*/IMPORT.defs'
      - 'lib/*/LICENSE'
      - 'README.md'



jobs:
  build:

    name: Valgrind
    runs-on: ubuntu-20.04
    container: ubuntu:20.04



    ###
    ### Steps to run
    ###
    steps:



      ### Fetch the code
      #
      - uses: actions/checkout@v2



      ### Install build environment tools
      #
      - run: apt-get update -y
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: apt-get install -y   gcc gzip make procps socat tar wget   autoconf git libtool m4   valgrind
        env:
          DEBIAN_FRONTEND: noninteractive



      ### Build
      #
      - run: ./bootstrap.sh
      - run: ./configure --enable-everything
      - run: make
      - run: make valgrind
