name: Code QA - Autoscan



on:
  workflow_dispatch:

  push:
    branches:
      - master
    tags:
      - '*'
    paths-ignore:
      - '.github/*.md'
      - '.github/workflows/**'
      - '.gitignore'
      - 'ChangeLog'
      - 'COPYING'
      - 'contrib/**'
      - 'doc/**'
      - 'install/**'
      - 'lib/*/IMPORT.defs'
      - 'lib/*/LICENSE'
      - 'README.md'

  pull_request:
    branches:
      - master
    paths-ignore:
      - '.github/*.md'
      - '.github/workflows/**'
      - '.gitignore'
      - 'ChangeLog'
      - 'COPYING'
      - 'contrib/**'
      - 'doc/**'
      - 'install/**'
      - 'lib/*/IMPORT.defs'
      - 'lib/*/LICENSE'
      - 'README.md'



jobs:
  code-qa-autoscan:

    name: Code QA - Autoscan - Scan for configure.ac changes
    runs-on: ubuntu-20.04
    container: ubuntu:20.04

    steps:



      ### Fetch the code
      #
      - uses: actions/checkout@v2



      ### Install build environment tools
      #
      - run: apt-get update -y
        env:
          DEBIAN_FRONTEND: noninteractive
      - run: apt-get install -y   autoconf
        env:
          DEBIAN_FRONTEND: noninteractive



      ### Run autoscan
      #
      - name: Run autoscan, check for changes
        run: |
          cp configure.scan configure.scan.GIT
          autoscan
          diff -u configure.scan.GIT configure.scan



      ### If changes are detected, show this help hint
      #
      - name: "Failed? Here's what you should do to fix the issue:"
        if: failure()
        run: |
          echo -e "Check the autoscan-related section in this document:\n\n    https://github.com/a2o/snoopy/blob/master/doc/HACKING-QA.md#autoscan\n\n"
